### ISSUE TITLE
Setting Tags to Sync to Mautic

### ISSUE THREAD

**Issue by mcollopy** [veda-consulting-company/uk.co.vedaconsulting.mautic#13]
Hi, after the first push, my tags did not sync to Mautic, and so I need some clarification of the configuration.

The instructions suggest "You can enable synchronization of tags" however as there's no option for that, I assumed it was the default, as the other options either limit or disable:
- No tag synchronization 
- Restrict tag synchronization to a tag-set 
- Push and pull without removing any tags

How can the extension be configured to sync all tags?  Including both adding and removing?
Removing would be helpful if rules are being used to tag for the purposes of targeting and message selection. 
If one of the above is selected, as they are radio select, how could they be unselected again?

Once again, great extension, appreciate your good work here.  Thanks.

**Comment by simonjohnparker** [comment]
Hi, 

Have you enabled the Mautic tag set in CiviCRM?

**Comment by mcollopy** [comment]
Yes I have enabled a Tagset - still not working.
Have just run the Mautic push sync manually, and the tag is not visible.
Have you had success with this?  Which option did you choose?
Thanks.

**Comment by simonjohnparker** [comment]
Sorry, I've just re-read your first post. As far as I know, it's limited to just the tag-set, not all tags.

That being said, I've just tested and I'm experiencing the same behaviour you describe with a tagset. I am able to get tags pushed from Mautic -> CiviCRM (which is all I personally use it for at this time) but not vice versa. 

There are some other issues with the way the extension is handling many contacts sync plus some problems with webhooks overload which is being investigated at the moment as a priority. I'll see if this can be looked at after.

**Comment by simonjohnparker** [comment]
The syncing of Mautic tags to a CiviCRM tag set should now be working in the latest version.

**Comment by mcollopy** [comment]
Hi, reopening this as I'm not successfully getting tags to sync:

- yes using a tag set 'Mautic'
- tags on Drupal not on Mautic - doesn't sync
- tags on Mautic not Drupal - gets cleared on Mautic
- tags on both  -sync is preserved
- removed on Drupal - not removed on Mautic

My reading of the documentation is that using a tag set should be a 2-way sync - is that correct?
If not using a tag set, they get added, not removed - again 2 way or 1 way?

Thanks

**Comment by mcollopy** [comment]
Issue persists after upgrading to v1.3
- Tags not syncing for specified tagset 'Mautic'
Please advise, thanks.
